package com.ligero.cli;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Edits generated source files by inserting lines just above marker
 * comments. This is how {@code ligero generate} auto-registers a new
 * artifact in its module (the same trick Angular's CLI uses): the
 * generated code carries anchors like {@code // ligero-cli:beans} and new
 * bindings/routes/modules are woven in before them.
 */
final class SourceEditor {

    static final String BEANS_ANCHOR = "// ligero-cli:beans";
    static final String ROUTES_ANCHOR = "// ligero-cli:routes";
    static final String MODULES_ANCHOR = "// ligero-cli:modules";
    static final String IMPORTS_ANCHOR = "// ligero-cli:imports";

    private SourceEditor() {
    }

    /**
     * Inserts {@code line} (indented to match the anchor) immediately before
     * the first occurrence of {@code anchor}. Idempotent: if the exact line
     * is already present, the file is left untouched.
     */
    static void insertBeforeAnchor(Path file, String anchor, String line) throws IOException {
        List<String> lines = new java.util.ArrayList<>(Files.readAllLines(file));
        int anchorIndex = -1;
        for (int i = 0; i < lines.size(); i++) {
            String trimmed = lines.get(i).trim();
            if (trimmed.equals(line.trim())) {
                return; // already registered
            }
            if (anchorIndex < 0 && trimmed.equals(anchor)) {
                anchorIndex = i;
            }
        }
        if (anchorIndex < 0) {
            throw new IllegalStateException(
                "Anchor '" + anchor + "' not found in " + file.getFileName()
                + " — was it generated by 'ligero new'? You can register it manually.");
        }
        String indent = leadingWhitespace(lines.get(anchorIndex));
        lines.add(anchorIndex, indent + line);
        Files.write(file, lines);
    }

    /**
     * Ensures {@code import ...;} is present, inserting it just before the
     * {@link #IMPORTS_ANCHOR}. No-op if the import already exists.
     */
    static void ensureImport(Path file, String importStatement) throws IOException {
        insertBeforeAnchor(file, IMPORTS_ANCHOR, importStatement);
    }

    private static String leadingWhitespace(String line) {
        int i = 0;
        while (i < line.length() && Character.isWhitespace(line.charAt(i))) {
            i++;
        }
        return line.substring(0, i);
    }
}
